---
sysctl_conf_template: sysctl.conf
rc_local_template: rc.local
security_limits_conf: limits.conf
security_nproc_conf: 20-nproc.conf
se_linux_conf: selinux.config

jdk_sh_template: jdk.sh
jdk_csh_template: jdk.csh

yum_install_packages:
 - nmap-ncat
 - bind-utils
 - MySQL-python
 - bzip2
 - unzip
 - wget
 - rng-tools
 - openssl-devel
 - zlib-devel
 - krb5-devel
 - krb5-workstation

yum_master_packages:
 - tmux
 - clustershell

yum_remove_packages:
 - mariadb-libs
